dist: bionic
addons:
 apt:
  packages: [doxygen, graphviz]
language: python
python:
  - "3.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip3 install --upgrade pip
  - pip3 install setuptools
  - pip3 install Sphinx
  - pip3 install platformio
  - platformio update

script:
  - make -C test
  - make -C docs html linkcheck
  - git diff --exit-code

notifications:
  email:
    recipients:
      - secure: "vsmdztqdhvF9aYlZ7j3whGFcOqlewwmIHCBiUYsIY8xRPj9W1bznct3g+D7A4Q+3Yvfi3Ag32cZT/e2aMquAygPhkVPbkBLAJrRpj1UPtk6nSk9WgeNJ4SiO8xjB6XAAV4kAJxeVLCbtOqNX+ifDmfDEdAuDiCNUzswe5fq7SVXvV9LHhDXvj4hHtfwMRYIYi2lRDMVvH//zIjMee7sj5Xqr1Y5d/hm2s/hffKFr0pSy3o45aI4De1Gkum91Rr464k3dcp9lArsKN2DsdllqA5xoGT4GQiGDeWr1fZKt1DDN7bvMWlun6hHSMI+IOyXF/uxzsKXrIq7X4d1txRDT2LeAcEyA+YdvMsViXPs8hEeKDWBkbMnAxbKbgDKAhu71J0RS5atTlVic+6sGwas5fE9i54jDstlJU0Bg6AZBZextEkjzU8RLHs6jSbQNYXcVV0tWGt9/ciIU9VBMoDIoXeteeZ13aWvDNXX6w/WT+78uaGjh6KLQC+DNoN0aYsAbWWRuFEgVHPw24nTJIa6HIf8+FnR6rFBCII2yI1PRMEbKrdSWRAK7Oi+5dBvqbbPXIRF3hY1hgYu9rN8/nywv2/dXgahHyW0kgtmONbWK8udLDCT9ofp78FWoTq0mZFf1WtGUcWdnUpBN+7Q3Uaq1rH7fe6D90aG/qTkzp1rTYlk="
